services:
  prism:
    container_name: prism
    image: ghcr.io/lone-cloud/prism:latest
    ports:
      - "8080:8080"
    volumes:
      - prism-data:/app/data
    env_file:
      - .env
    restart: unless-stopped

volumes:
  prism-data:
